### ISSUE TITLE
Adafruit_TSL2561_Unified::init() return true even if no sensor is attached!

### ISSUE THREAD

**Issue by beegee-tokyo** [adafruit/Adafruit_TSL2561#11]
**`Adafruit_TSL2561_Unified::init()`** checks the value read from **`TSL2561_REGISTER_ID`** against **`!(x & 0x0A)`**.
This is always true if there is no sensor is attached, because then the returned value is 0xFF.

According to the TSL2561 datasheet, the high 4 bits of **`TSL2561_REGISTER_ID`** should be 
**`0000`**
**`0001`**
**`0100`**
**`0101`**
So there is always at least two 0's in it. An additional check of the returned value agains 0xFF could detect if there is no sensor attached.
e.g.:
```
boolean Adafruit_TSL2561_Unified::init()
{
  /* Make sure we're actually connected */
  uint8_t x = read8(TSL2561_REGISTER_ID);
  if (x == 0xFF) {
    return false;
  }
  if (!(x & 0x0A))
  {
    return false;
  }
  _tsl2561Initialised = true;

  /* Set default integration time and gain */
  setIntegrationTime(_tsl2561IntegrationTime);
  setGain(_tsl2561Gain);

  /* Note: by default, the device is in power down mode on bootup */
  disable();

  return true;
}

```

**Comment by ladyada** [comment]
according to DS we have, 0x10 is for TSL2561 so just put that in :)

![image](https://user-images.githubusercontent.com/1214161/35164800-d65654f6-fd19-11e7-86d0-33f2d00e4073.png)

thankx!
