### ISSUE TITLE
Ask for code to obtain data from multiple sensors via I2C bus

### ISSUE THREAD

**Issue by bundit786** [adafruit/Adafruit_TSL2561#4]
Hi,

   I have Adafruit Lux sensor TSL2561 3 pcs and would like to read the light intensity (Lux) simultaneously from them. Can anyone guide for Arduino sketch to perform this task?

Thank you.
B.Bundit

**Comment by microbuilder** [comment]
You either need to change the I2C addresses use or use an I2C multiplexer (https://learn.adafruit.com/adafruit-tca9548a-1-to-8-i2c-multiplexer-breakout/overview), but can you please post this in the Adafruit support forums?  Github is really only used for pull requests or bugs in the code, and isn't monitored by our support team.  Thanks!
