### ISSUE TITLE
U8GILB compatibility wth TSL2561

### ISSUE THREAD

**Issue by zetalif** [adafruit/Adafruit_TSL2561#6]
Hi,

I've tried U8GILB with TSL2561 unified library with Arduino due and oled 0.96". It seems that after the first output ok it is not possible to refresh the screen and the output is ever 65536.
Removing U8GLIB instructions the sketch works well.
May someone help me about this issue ?

**Comment by ladyada** [comment]
hiya if you're still having this issue please re-open!
